lzc-sdk-version: "0.1"
name: Kikoeru
package: cloud.lazycat.zpp.kikoeru
version: 0.7.3
description: 一个自托管的DLsite音声作品整理和媒体播放软件，为你提供极致的音声视听体验。
homepage: https://github.com/vscodev/kikoeru
author: vscodev
application:
  subdomain: kikoeru
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://kikoeru.cloud.lazycat.zpp.kikoeru.lzcapp:2333/
services:
  kikoeru:
    image: registry.lazycat.cloud/czyt/vscodev/kikoeru:3f8ef10807ee7a17
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
      - UMASK=22
      - KIKOERU_LOCALE=zh-CN
    binds:
      - /lzcapp/var/data:/opt/kikoeru/data/
